// <auto-generated />
using System;
using System.Collections.Generic;
using LangVet.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LangVet.Infrastructure.Migrations
{
    [DbContext(typeof(LangVetContext))]
    [Migration("20241110155430_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.HighlightedTerms", b =>
                {
                    b.Property<Guid>("HighlightedTermId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("termDefinition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("termDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("termLink")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("termName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("termSubCluster")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("HighlightedTermId");

                    b.ToTable("highlightedTerms");
                });

            modelBuilder.Entity("Domain.Entities.Input", b =>
                {
                    b.Property<Guid>("InputId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("InputFile")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("InputName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InputText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("InputId");

                    b.ToTable("inputs");
                });

            modelBuilder.Entity("Domain.Entities.MarkedDocument", b =>
                {
                    b.Property<Guid>("MarkedDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DictionaryId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileDownloadLink")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("InputDocumentId")
                        .HasColumnType("uuid");

                    b.HasKey("MarkedDocumentId");

                    b.ToTable("markedDocuments");
                });

            modelBuilder.Entity("Domain.Entities.OutputTerms", b =>
                {
                    b.Property<Guid>("OutputTermsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DictionaryId")
                        .HasColumnType("uuid");

                    b.Property<List<Guid>>("HighlightedTermIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.HasKey("OutputTermsId");

                    b.ToTable("outputTerms");
                });
#pragma warning restore 612, 618
        }
    }
}
